FORMAT: 1A

# Implementation by Z

## Message B [/messageb]
- Response 200 (application/json)

        { "msg": "THIS IS B" }


## Message A [/messagea]

### Retrieve [GET]
- Response 200 (application/json)

        { "msg": "Hello colour!" }