FORMAT: 1A

# Style Guide Test

## MZ's Message [/message]

This is the message resource to ..... 

- one 
- two 
- thirds

asdsadas

### Retrieve [GET]
- Response 200 (application/json)

        { "msg": "Hello colour!" }